### ISSUE TITLE
issue when loading plugin

### ISSUE THREAD

**Issue by rgeneaux** [BenediktBurger/pymodaq_plugins_basler#6]
Hi,
we tried testing the plugin but pymdoaq fails to load it,
we get the following error

pymodaq.viewer2D_plugins - WARNING - daq_2Dviewer_Basler plugin couldn't be loaded due to some missing packages or errors: 'type' object is not subscriptable

any idea what could cause that?

Thanks!

**Comment by BenediktBurger** [comment]
Which Python version are you using?
I guess it relates to the use of type hints.

**Comment by BenediktBurger** [comment]
Thanks for testing. I released this modified version.
